apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: shop
          resources:
            requests:
              cpu: "50m"

