apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-deployment.yaml

configMapGenerator:
  - name: shop-config
    behavior: replace
    literals:
      - SHOP_MSG=Hej från PROD overlay
